Level up
wobgob/azerothcore-wotlk pull request #36
Opened 2021-09-21 09:05 UTC by ThatsSoTrinda

## Changes Proposed:
-  This module will give the player a Level n Loot Box at levels: 10, 19, 29, 39, 49, 59, 60, 64. (Hereafter referred to as milestone levels)

## Issues Addressed:

- Closes #27 

## Tests Performed:

- Tested on WoW 3.3.5a using Windows 10 Pro x64
- All milestone levels grant a loot box via ingame mail.

## How to Test the Changes:

1. Level a character to a milestone level.
2. A system message will appear prompting you to check your mail for a reward
3. Grab the level loot box from your mail, and open it.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-21 09:55 UTC, jarrodjeffi requested changes
Great work so far! The logic is sound and it's just a manner of polishing off the rough edges.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/README.md
> +# SKELETON - Module template
Could we fix up the READMEs

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/README_ES.md
> + [English](README.md) | [Español](README_ES.md)
We can safely delete this file

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/README_example.md
> +# MY_NEW_MODULE
This just needs a little fixing up and should be the main `README.md`

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/conf/conf.sh.dist
> +	$MOD_SKELETON_ROOT"/sql/auth/base/"
I typically rename these `MOD_SKELETON_ROOT` to something like `MOD_LEVEL_UP_ROOT`.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/include.sh
> +MOD_SKELETON_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/" && pwd )"
Same here.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/README.md
> +# NEW MODULE - SQL BEST PRACTICES
Either remove this file or change this to `# LEVEL UP - SQL BEST PRACTICES`

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/auth/base/development.sql
> +-- Put only sql data in this file (insert, update, replace into, delete etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/auth/base/production.sql
> +-- Put only sql data in this file (insert, update, replace into, delete etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/auth/base/structure.sql
> +-- Put only sql structure in this file (create table if exists, delete table, alter table etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/characters/base/development.sql
> +-- Put only sql data in this file (insert, update, replace into, delete etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/characters/base/production.sql
> +-- Put only sql data in this file (insert, update, replace into, delete etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/characters/base/structure.sql
> +-- Put only sql structure in this file (create table if exists, delete table, alter table etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/world/base/development.sql
> +-- Put only sql data in this file (insert, update, replace into, delete etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/world/base/production.sql
> +-- Put only sql data in this file (insert, update, replace into, delete etc...).
Delete.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/sql/world/base/structure.sql
> +INSERT INTO `item_template` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`, `name`, `displayid`, `Quality`, `Flags`, `FlagsExtra`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `Allow
This all seems fine. I assume this is what you exported out of the database?

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +const std::string SUBJECT = "Loot box reward";
`"Level up reward"` would be more appropriate.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +        uint8 playerCurLevel = player->getLevel();
I'd prefer `playerCurrentLevel`. If you're not using `oldLevel` could you comment it out like `uint8 /*oldLevel*/` so the compiler doesn't complain.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUp_loader.h
> +void AddMyModuleScripts()
Probably best if this was `AddLevelUpScripts()`.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUp_loader.h
> +    AddMyPlayerScripts();
`AddLevelUpPlayerScripts()`

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +        MailSender sender(5126979);
Can we make the sender a config variable. Something like `LevelUp.Sender` with default value `5126979`.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +void AddMyPlayerScripts()
`AddLevelUpPlayerScripts()`

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/conf/LevelUp.conf.dist
> +########################################
You'll have to add `LevelUp.Sender` here with documentation. You'll need a `LevelUpWorld` script to load the config. `mod-loot-box` has an example.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +    LevelUpPlayer() : PlayerScript("LevelUp") { }
`"LevelUp"` should be `"LevelUpPlayer"`

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +        if (sConfigMgr->GetOption<bool>("LevelUp.Enable", false))
I should have mentioned the code style beforehand. Anything that can be nested has its brace on the same line like `if`, `switch`, `for`. Functions and such (which can't be nested in C at least) have their brace on the next line. I like the [Linux kernel coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html) for a general idea of the vibe I'm going for.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +                break;
You could add a `return` here instead of a `break` and then move `playerLevelUpMessage()` below the switch statement to clean it up. You had me stumped since the repeated `playerLevelUpMessage()` seemed like a code smell.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +                sendRewardToPlayer(player, 5621810);
Could we also get each box in its own config variable: `LevelUp.Ten`, `LevelUp.Nineteen`, ..., `LevelUp.SixtyFour`.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +    void playerLevelUpMessage(Player *player, uint8 playerCurLevel)
`playerCurrentLevel`

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUp_loader.h
> +void AddMyPlayerScripts();
`AddLevelUpPlayerScripts()`

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +            sLog->outError("[Mod-Level-Up] Item ID is invalid: %u", itemId);
Could we have this as `[mod-level-up]` please.

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +        ChatHandler(player->GetSession()).PSendSysMessage("Congratulations on reaching |cff4CFF00Level %d|r!", playerCurLevel);
This seems a bit too similar to the game's in-built congratulations. Perhaps make this one line like "You've reached a milestone! Go check your mailbox for something special."

2021-09-21 09:55 UTC, jarrodjeffi commented on modules/mod-level-up/src/LevelUpPlayer.cpp
> +/*
Remove the copyright.

2021-09-21 10:09 UTC, ThatsSoTrinda commented on modules/mod-level-up/sql/world/base/structure.sql
> +INSERT INTO `item_template` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`, `name`, `displayid`, `Quality`, `Flags`, `FlagsExtra`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `Allow
Yep, that's all exported from the DB

2021-09-25 02:54 UTC, jarrodjeffi approved these changes

2021-09-25 02:58 UTC, merged